VoidChestMenu:
  title: "%voidchest% &7| &fVoidChest Menu"
  # rows is ignored if you have a structure
  # IF YOU DON'T HAVE A STRUCTURE YOU NEED TO SPECIFY ITEM SLOTS
  rows: 6
  animation: true
  # Default action is executed when you click an item without a specific action.
  defaultAction: voidchest:nothing
  # The bottom inventory action is set to nothing by default
  # You can change it to voidchest:open_container to open the container OR voidchest:open_upgrades to open the upgrades menu
  #bottomInventoryAction: voidchest:nothing
  structure:
    - "# # # # # # # # #"
    - "# A # C # P # U #"
    - "# # # # # # # # #"
    - "# H # L # T # B #"
    - "# # # # # # # # #"
    - "S # # # E # # # O"

  items:
    # Without Structure example:
    #"#":
    #  item: BLACK_STAINED_GLASS_PANE
    #  name: " "
    #  lore: [ ]
    #  glow: false
    #  amount: 1
    #  action: voidchest:nothing
    #  slots: [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ... 53 ]
    "#":
      item: BLACK_STAINED_GLASS_PANE
      name: " "
      lore: [ ]
      glow: false
      amount: 1
      action: voidchest:nothing

    "A":
      item: DIAMOND
      name: "&6&lAuto Sell"
      lore:
        - "&7Enable automatic selling of contents."
        - "&7Status: &e%status_auto_sell%"
        - ""
        - "&eClick to toggle."
      glow: true
      amount: 1
      animation: "wave"
      colors:
        - "#FFE066"
        - "#FFB347"
        - "#FFA500"
        - "#FF8C00"
        - "#FF4500"
      action: voidchest:toggle_auto_sell

    "C":
      item: HOPPER
      name: "&6&lChunk Collector"
      lore:
        - "&7Collect items in the chunk automatically."
        - "&7Status: &e%status_chunk_collector%"
        - ""
        - "&eClick to toggle."
      glow: true
      amount: 1
      animation: "wave"
      colors:
        - "#FFA07A"
        - "#FF7F50"
        - "#FF6347"
        - "#FF4500"
        - "#FF0000"
      action: voidchest:toggle_chunk_collector

    "P":
      item: TNT
      name: "&c&lPurge Non-Sellable"
      lore:
        - "&7Delete non-sellable items automatically."
        - "&7Status: &e%status_purge%"
        - ""
        - "&eClick to toggle."
      glow: true
      amount: 1
      animation: "wave"
      colors:
        - "#FFB6C1"
        - "#FF69B4"
        - "#FF1493"
        - "#DB7093"
        - "#C71585"
      action: voidchest:toggle_purge

    "U":
      item: FEATHER
      name: "&b&lUpgrades"
      lore:
        - "&7Open the upgrades menu to enhance your VoidChest."
      glow: true
      amount: 1
      animation: "wave"
      colors:
        - "#87CEFA"
        - "#00BFFF"
        - "#1E90FF"
        - "#4682B4"
        - "#5F9EA0"
      action: voidchest:open_upgrades

    "H":
      item: ARMOR_STAND
      name: "&b&lHologram Display"
      lore:
        - "&7Toggle the hologram for this VoidChest."
        - "&7Status: &e%status_hologram%"
        - ""
        - "&eClick to toggle."
      glow: true
      amount: 1
      animation: "wave"
      colors:
        - "#D8BFD8"
        - "#DA70D6"
        - "#BA55D3"
        - "#9932CC"
        - "#8A2BE2"
      action: voidchest:toggle_hologram

    "L":
      item: LAVA_BUCKET
      name: "&d&lVoidChest Charge"
      lore:
        - "&7Add one hour of charge time to your VoidChest."
        - ""
        - "&7Current Charge: &e%charge%"
        - "&7Price per Renewal: &e$%price%"
        - "&7Renewal Time: &e%renewal%"
      glow: true
      amount: 1
      animation: "wave"
      colors:
        - "#FF69B4"
        - "#FF1493"
        - "#DB7093"
        - "#C71585"
        - "#800080"
      action: voidchest:add_charge

    "T":
      item: SLIME_BALL
      name: "&a&lTransfer Non-Sellable"
      lore:
        - "&7Transfer non-sellable items to a linked chest."
        - "&7Status: &e%status_transfer_non_sellable%"
        - ""
        - "&eClick to toggle."
      glow: true
      amount: 1
      animation: "wave"
      colors:
        - "#98FB98"
        - "#7CFC00"
        - "#32CD32"
        - "#228B22"
        - "#006400"
      action: voidchest:toggle_transfer_non_sellable

    "B":
      item: GOLD_INGOT
      name: "&9&lBank Transfer"
      lore:
        - "&7Choose whether income goes to your bank."
        - "&7Current Destination: &e%status_bank%"
        - ""
        - "&eClick to toggle."
      glow: true
      amount: 1
      animation: "wave"
      colors:
        - "#87CEEB"
        - "#4682B4"
        - "#4169E1"
        - "#1E90FF"
        - "#0000CD"
      action: voidchest:toggle_bank

    "O":
      item: CHEST
      name: "&6&lChest Inventory"
      lore:
        - "&7Access the inventory of your VoidChest."
        - ""
        - "&eClick to open."
      glow: true
      amount: 1
      animation: "wave"
      colors:
        - "#F0E68C"
        - "#FFD700"
        - "#FFA500"
        - "#FF8C00"
        - "#FF4500"
      action: voidchest:open_container

    "S":
      item: BOOK
      name: "&b&lStatistics"
      lore:
        - "&8&m---------------------"
        - " &6&lOwner: &e%owner%"
        - " &a&lVoidChest: &e%voidchest%"
        - " &b&lBooster: &e%booster%x"
        - " &a&lMoney Made: &e$%money%"
        - " &3&lItems Sold: &e%items_sold%"
        - " &4&lItems Purged: &e%items_purged%"
        - "&8&m---------------------"
      glow: false
      amount: 1
      animation: "wave"
      colors:
        - "#B0E0E6"
        - "#ADD8E6"
        - "#87CEFA"
        - "#87CEEB"
        - "#4682B4"
      action: voidchest:nothing

    "E":
      item: PLAYER_HEAD
      name: "&c&l» &e&lExit &c&l«"
      lore: [ ]
      skullProperty: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDQ2NjRlZGVhNzAxOTMzMjZhYTMxZjhmNTBmODBjMjkzN2I1YThmMDczNThhNWIwODQ5ZGRmNWI1YjJjOGMzNiJ9fX0="
      frames:
        0:
          item: PLAYER_HEAD
          skullProperty: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzY2ZmU5NzM4YTY5M2NlMjlkZWY1MmU3OTQ0OTNhZTAwMGVhYmE3MWJhNjYwNTY5MDY1ZWE2NjI4NTEzNTQxZiJ9fX0="
          amount: 1
          glow: true
      glow: true
      animation: "wave"
      colors:
        - "#FF0000"
        - "#DC143C"
        - "#B22222"
        - "#8B0000"
        - "#800000"
      action: voidchest:close
