# ##################################################################################
#                                                                                  #
# __      ______ _____ _____   _____ _    _ ______  _____ _______                  #
# \ \    / / __ \_   _|  __ \ / ____| |  | |  ____|/ ____|__   __|                 #
#  \ \  / / |  | || | | |  | | |    | |__| | |__  | (___    | |                    #
#   \ \/ /| |  | || | | |  | | |    |  __  |  __|  \___ \   | |                    #
#    \  / | |__| || |_| |__| | |____| |  | | |____ ____) |  | |                    #
#     \/   \____/_____|_____/ \_____|_|  |_|______|_____/   |_|                    #
#                                                                                  #
# ##################################################################################

# Configuration file for Options
Options:

  # Debug option
  debug: false

  # Proxy option
  proxy: false

  # Secret option
  secret: "SECRET HERE"

  # Locale option
  locale: "en_US"

  # WARNING: Only use this feature if you know what you're doing.
  #
  # In case of you having issues with voidchests being deleted upon a restart, increase the number by a bit.
  #
  # How many seconds should the plugin wait before loading data (voidchests, player related data, etc.)
  # This will allow worlds and other things to load before voidchest so that you can avoid issues such as voidchest
  # attempting to load voidchests in worlds that have yet to load.
  #
  # This should only be modified if servers are having issues with worlds loading after the voidchest plugin has loaded.
  # Recommended load-delay interval is any number from 1 to 10, the highest, the more time the data will delay to load.
  #
  # Any number that is < 1 will make the plugin instantly load data when the plugin enabled as well.
  # Is NOT RECOMMENDED to set this to < 2.
  load delay: 5

  # Experimental features option
  experimental features: false

  # Metrics option
  metrics: true

  # Discord option
  discord: false

  # Updater option
  updater:
    enabled: true

  # VoidChest command option
  commands:
    voidchest: true
    voidchest admin: true

  database:
    type: "File" #Types File, SQLite, MySQL, PostgreSQL, MongoDB

    # SQL database options
    SQL:
      host: "localhost"     # SQL database host
      port: 3306            # SQL database port
      user: "youruser"      # SQL database username
      password: "yourpassword"   # SQL database password
      database: "VoidChest"   # SQL database name
      users table name: "voidchest_users"   # SQL table for users
      voidchests table name: "voidchest_voidchests"   # SQL table for voidchests
      SQLite file name: "voidchest"   # SQLite file name

    # MongoDB options
    MongoDB:
      host: "localhost"     # MongoDB host
      port: 27017           # MongoDB port
      user: "youruser"      # MongoDB username
      password: "yourpassword"   # MongoDB password
      database: "voidchest"   # MongoDB database name
      users collection: "voidchest_users"   # MongoDB collection for users
      voidchest collection: "voidchest_voidchests"   # MongoDB collection for voidchests

  # Certain timings are automatically converted into d,h,m,s.
  # For example, charge time, hologram sell interval, etc.
  # By changing these, you can modify the text to your liking.
  time format:
    second: second
    seconds: seconds
    minute: minute
    minutes: minutes
    hour: hour
    hours: hours
    day: day
    days: days
    invalid: Invalid

  money format: "##.####"

  # Available plugins: Vault, TheNewEconomy, VoidChest, Custom
  #
  # VoidChest built in economy only supports EXP levels for charge upgrades and payouts.
  # Use "Custom" only if you know what you're doing, otherwise consult the developers.
  economy:
    charge: "Vault"
    upgrades: "Vault"
    payout: "Vault"

  # Available modes: EXP and LEVELS
  void chest economy mode: "EXP"

  # Should the plugin attempt to hook to one of the plugins: WildStacker, UltimateStacker, SpaceStacker, RoseStacker, zItemStacker, CloudSpawners, None
  stacker: "None"

  # Available plugins: SuperiorSkyblock2, FabledSkyBlock, SaberFactions, MysqlEconomyBank, RoyaleEconomy, Custom, None
  #
  # Use "Custom" only if you know what you're doing, otherwise consult the developers.
  bank: "None"

  # Available plugins: SaberFactions, SupremeFactions, FactionsUUID, Custom and None
  #
  # Use "Custom" only if you know what you're doing, otherwise consult the developers.
  bank tnt: "None"

  # Available hologram support from other plugins: VoidChest, HolographicDisplays, Holograms, CMI, DecentHolograms, FancyHolograms.
  hologram:
    plugin: "VoidChest"
    update interval: 20


  # Ignore item meta option
  ignore item meta: true

  # Should all voidchests have a single sell interval?
  # Set to false if you want voidchests to have different sell intervals.
  single task: false

  # The interval is being run in seconds. This will only be selected if the path can't be found in the voidchest's file itself
  # or when you have single task enabled.
  sell interval: 10

  # Chunk see options
  chunk see:
    Y central: 0
    Y up: 0
    Y down: 0
    effect:
      type: "VILLAGER_HAPPY"
      interval: 20

  sell message:
    enabled: false
    interval: 60

    offline:
      enabled: false
      message delay: 50
