name: ${pluginName}
version: ${version}
main: ${packageName}.VoidChestPlugin
description: "${description}"
author: '${author}'
voidchest-api-version: "${voidchestAPIVersion}"
folia-supported: true
softdepend: [ Vault, FabledSkyBlock, MysqlEconomyBank,
              RoyaleEconomy, Factions, SuperiorSkyblock2,
              CMI, DecentHolograms, Holograms,
              HolographicDisplays, RoseStacker, SpaceStacker,
              UltimateStacker, WildStacker, ZItemStacker,
              DynamicShop, CloudSpawners, ShopGUIPlus,
              FancyHolograms, PlaceholderAPI ]
api-version: 1.13
libraries:
  - org.mongodb:mongo-java-driver:3.12.13
  - mysql:mysql-connector-java:8.0.32
  - org.xerial:sqlite-jdbc:3.41.2.1
  - com.google.guava:guava:31.1-jre
  - org.postgresql:postgresql:42.6.0
  - commons-io:commons-io:2.11.0
  - commons-lang:commons-lang:2.6
  - commons-codec:commons-codec:1.15
