name: "&a&l%voidchest% VoidChest Inventory"
size: 54
animation:
  enabled: true
navigation:
  cancel:
    item: ANVIL
    title: "&8&l» &e&lExit &8&l«"
    amount: 1
    lores: [ ]
    show all attributes: false
    glow: false
    slot: 4
    animated: true
    animation: "wave"
    colors:
      - "#48D1CC"
      - "#778899"
      - "#55FF55"
      - "#FF1493"
    commands: [ ]
    commands cooldown:
      RIGHT: 0
      LEFT: 0
      MIDDLE: 0
  back:
    item: PAPER
    title: "&8&l» &e&lBack &8&l«"
    amount: 1
    lores: [ ]
    show all attributes: false
    glow: false
    slot: 2
    animated: true
    animation: "wave"
    colors:
      - "#48D1CC"
      - "#778899"
      - "#55FF55"
      - "#FF1493"
    commands: [ ]
    commands cooldown:
      RIGHT: 0
      LEFT: 0
      MIDDLE: 0
  next:
    item: BOOK
    title: "&8&l» &e&lNext &8&l«"
    amount: 1
    lores: [ ]
    show all attributes: false
    glow: false
    slot: 6
    animated: true
    animation: "wave"
    colors:
      - "#48D1CC"
      - "#778899"
      - "#55FF55"
      - "#FF1493"
    commands: [ ]
    commands cooldown:
      RIGHT: 0
      LEFT: 0
      MIDDLE: 0
custom item:
  navigation:
    '0':
      item: BOOK
      title: "&b&lStatistics"
      lores:
        - '&8&l&m---------------------'
        - ' &c&l* Owner -> &c%owner%'
        - ' &6&l* &6VoidChest -> %voidchest%'
        - ' &b&l* &bBooster -> %booster%x'
        - ' &a&l* &aMoney made -> $%money%'
        - ' &3&l* &3Items sold -> %items_sold%'
        - ' &4&l* &4Items purged -> %items_purged%'
        - ' &6&l* &6Items stored -> %items_stored%'
        - '&8&l&m---------------------'
      glow: false
      show attributes: false
      amount: 1
      animated: true
      animation: "wave"
      colors:
        - "#F3F8FA"
        - "#A2CCE3"
        - "#68A4C4"
        - "#32627B"
        - "#1E4356"
      commands: [ ]
      commands cooldown:
        RIGHT: 0
        LEFT: 0
        MIDDLE: 0
  gui:
    '11':
      item: GOLD_INGOT
      title: "&a&lAuto Sell"
      lores:
        - "&7Should this voidchest sell contents?"
        - " "
        - "&7Status %status_auto_sell%"
        - " "
        - "&7Click to &a%!status_auto_sell%&7 this setting."
      glow: false
      show attributes: false
      amount: 1
      animated: true
      animation: "wave"
      colors:
        - "#F3F8FA"
        - "#A2CCE3"
        - "#68A4C4"
        - "#32627B"
        - "#1E4356"
      action: TOGGLE_AUTO_SELL
      commands: [ ]
      commands cooldown:
        RIGHT: 0
        LEFT: 0
        MIDDLE: 0
    '13':
      item: MAGMA_CREAM
      title: "&a&lCollect Chunk Items"
      lores:
        - "&7Should this voidchest collect items"
        - "&7inside this chunk and sell them if possible?"
        - " "
        - "&7Status %status_chunk_collector%"
        - " "
        - "&7Click to &a%!status_chunk_collector%&7 this setting."
      glow: false
      show attributes: false
      amount: 1
      animated: true
      animation: "wave"
      colors:
        - "#F3F8FA"
        - "#A2CCE3"
        - "#68A4C4"
        - "#32627B"
        - "#1E4356"
      action: TOGGLE_CHUNK_COLLECTOR
      commands: [ ]
      commands cooldown:
        RIGHT: 0
        LEFT: 0
        MIDDLE: 0
    '15':
      item: ENDER_EYE
      title: "&a&lDelete Non-Sellable Items"
      lores:
        - "&7Should this voidchest delete items"
        - "&7that are not sellable?"
        - " "
        - "&7Status %status_purge%"
        - " "
        - "&7Click to &a%!status_purge%&7 this setting."
      glow: false
      show attributes: false
      amount: 1
      animated: true
      animation: "wave"
      colors:
        - "#F3F8FA"
        - "#A2CCE3"
        - "#68A4C4"
        - "#32627B"
        - "#1E4356"
      action: TOGGLE_PURGE
      commands: [ ]
      commands cooldown:
        RIGHT: 0
        LEFT: 0
        MIDDLE: 0
    '19':
      item: PAPER
      title: "&a&lInstant Collect Chunk Items"
      lores:
        - "&7Should this voidchest instant collect items"
        - "&7inside this chunk?"
        - " "
        - "&7Chunk Collector Status %status_chunk_collector%"
        - "&7Instant Collector Status %status_instant_collector%"
        - " "
        - "&7Click to &a%!status_instant_collector%&7 this setting."
      glow: false
      show attributes: false
      amount: 1
      animated: true
      animation: "wave"
      colors:
        - "#F3F8FA"
        - "#A2CCE3"
        - "#68A4C4"
        - "#32627B"
        - "#1E4356"
      action: TOGGLE_INSTANT_COLLECTOR
      commands: [ ]
      commands cooldown:
        RIGHT: 0
        LEFT: 0
        MIDDLE: 0
    '22':
      item: ARMOR_STAND
      title: "&a&lHologram"
      lores:
        - "&7Click to toggle this VoidChest's hologram"
        - ""
        - "&7Status: %status_hologram%"
        - ""
        - "&7Click to %!status_hologram%&7 the hologram."
      glow: false
      show attributes: false
      amount: 1
      animated: true
      animation: "wave"
      colors:
        - "#F3F8FA"
        - "#A2CCE3"
        - "#68A4C4"
        - "#32627B"
        - "#1E4356"
      action: TOGGLE_HOLOGRAM
      commands: [ ]
      commands cooldown:
        RIGHT: 0
        LEFT: 0
        MIDDLE: 0
    '25':
      item: LAVA_BUCKET
      title: "&d&lVoidChest Charge"
      lores:
        - '&7Click to add one hour charge to your VoidChest.'
        - ''
        - '&7Current Charge Time: &e%charge%'
        - '&7Price per renewal: &e$%price%'
        - '&7Renewal time per purchase: &e%renewal%'
      glow: false
      show attributes: false
      amount: 1
      animated: true
      animation: "wave"
      colors:
        - "#F3F8FA"
        - "#A2CCE3"
        - "#68A4C4"
        - "#32627B"
        - "#1E4356"
      action: ADD_CHARGE
      commands: [ ]
      commands cooldown:
        RIGHT: 0
        LEFT: 0
        MIDDLE: 0
    '29':
      item: SLIME_BALL
      title: "&d&lTransfer non sellables"
      lores:
        - "&7Click to toggle this VoidChest's transfer non sellables"
        - ""
        - "&7Status: %status_transfer_non_sellables%"
        - ""
        - "&7Click to %!status_transfer_non_sellables%&7 the transfer non sellables."
      glow: false
      show attributes: false
      amount: 1
      animated: true
      animation: "wave"
      colors:
        - "#F3F8FA"
        - "#A2CCE3"
        - "#68A4C4"
        - "#32627B"
        - "#1E4356"
      action: TOGGLE_TRANSFER_NON_SELLABLES
      commands: [ ]
      commands cooldown:
        RIGHT: 0
        LEFT: 0
        MIDDLE: 0
    '31':
      item: CHEST
      title: "&6&lChest Inventory"
      lores:
        - '&7&o{( Click me to open the chest inventory )}'
      glow: false
      show attributes: false
      amount: 1
      animated: true
      animation: "wave"
      colors:
        - "#F3F8FA"
        - "#A2CCE3"
        - "#68A4C4"
        - "#32627B"
        - "#1E4356"
      action: OPEN_CHEST
      commands: [ ]
      commands cooldown:
        RIGHT: 0
        LEFT: 0
        MIDDLE: 0
    '33':
      item: POTION
      title: "&a&lBank"
      lores:
        - "&7Click to toggle your income's direction."
        - ""
        - "&7Money goes to: %status_bank%"
        - ""
        - "&7Click to make your income go to your %!status_bank%&7 account."
      glow: false
      show attributes: false
      amount: 1
      animated: true
      animation: "wave"
      colors:
        - "#F3F8FA"
        - "#A2CCE3"
        - "#68A4C4"
        - "#32627B"
        - "#1E4356"
      action: TOGGLE_BANK
      commands: [ ]
      commands cooldown:
        RIGHT: 0
        LEFT: 0
        MIDDLE: 0