Shop-Items:
  - ==: VoidShopItem
    price: !!float '100'
    nbtContainer: '{Count:1b,id:"minecraft:diamond"}'
  - ==: VoidShopItem
    price: !!float '900'
    nbtContainer: '{Count:1b,id:"minecraft:diamond_block"}'
  - ==: VoidShopItem
    price: !!float '1000'
    nbtContainer: '{Count:1b,id:"minecraft:enchanted_golden_apple"}'
